name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
        env:
          Mongo_URI: ${{ secrets.Mongo_URI }}
          Mongo_URI_TEST: ${{ secrets.Mongo_URI_TEST }}
      - run: npm ci
      - run: npm test
